from app.repositories.produto_repository import ProdutoRepository

ITENS_PADRAO = {
    "Alimentos Principais": [
        "Arroz branco",
        "Feijão carioca",
        "Feijão preto",
        "Macarrão espaguete",
        "Macarrão parafuso",
        "Farinha de trigo",
        "Fubá",
        "Farinha de mandioca",
        "Tapioca",
        "Aveia",
        "Granola",
        "Pão de forma",
        "Pão francês",
        "Biscoito cream cracker",
        "Biscoito água e sal",
        "Batata inglesa",
        "Batata doce",
        "Mandioca",
        "Inhame",
        "Cenoura",
        "Beterraba",
        "Chuchu",
        "Abobrinha",
        "Tomate",
        "Alface",
        "Couve",
        "Brócolis",
        "Espinafre",
        "Banana",
        "Maçã",
        "Laranja",
        "Mamão",
        "Melancia",
        "Abacaxi",
        "Uva",
        "Frango (peito)",
        "Frango (coxa e sobrecoxa)",
        "Carne moída",
        "Patinho",
        "Acém",
        "Costela bovina",
        "Linguiça calabresa",
        "Linguiça toscana",
        "Peixe tilápia",
        "Sardinha em lata",
        "Atum em lata",
        "Ovos",
        "Leite integral",
        "Leite desnatado",
        "Iogurte natural",
        "Queijo mussarela",
        "Queijo prato",
        "Requeijão",
        "Manteiga",
        "Creme de leite",
        "Leite condensado",
    ],
    "Complementos": [
        "Óleo de soja",
        "Azeite de oliva",
        "Vinagre de álcool",
        "Vinagre de maçã",
        "Molho de tomate",
        "Extrato de tomate",
        "Maionese",
        "Ketchup",
        "Mostarda",
        "Shoyu",
        "Caldo de frango (tablete)",
        "Caldo de carne (tablete)",
        "Farinha de rosca",
        "Amido de milho (maisena)",
        "Fermento em pó",
        "Fermento biológico",
        "Açúcar refinado",
        "Açúcar cristal",
        "Açúcar mascavo",
        "Adoçante",
        "Mel",
        "Café em pó",
        "Achocolatado em pó",
        "Chocolate em pó",
        "Coco ralado",
        "Gelatina",
        "Pó para preparo de suco",
        "Refrigerante",
        "Água mineral",
        "Suco de caixinha",
        "Cerveja",
        "Vinho tinto",
        "Vinho branco",
    ],
    "Temperos": [
        "Sal refinado",
        "Sal grosso",
        "Pimenta-do-reino",
        "Pimenta vermelha",
        "Alho",
        "Cebola",
        "Louro",
        "Orégano",
        "Manjericão",
        "Coentro",
        "Cheiro-verde",
        "Cominho",
        "Colorau (urucum)",
        "Páprica defumada",
        "Páprica doce",
        "Açafrão (cúrcuma)",
        "Canela em pó",
        "Cravo",
        "Noz-moscada",
        "Tempero baiano",
        "Tempero completo",
        "Chimichurri",
        "Alecrim",
        "Tomilho",
        "Curry",
    ],
    "Higiene e Limpeza": [
        "Sabão em pó",
        "Sabão em barra",
        "Detergente líquido",
        "Amaciante de roupas",
        "Água sanitária",
        "Desinfetante",
        "Limpador multiuso",
        "Limpa vidros",
        "Limpador de banheiro",
        "Pano de prato",
        "Esponja de lavar louça",
        "Palha de aço",
        "Rodo",
        "Vassoura",
        "Lixeira com tampa",
        "Saco de lixo (15L)",
        "Saco de lixo (30L)",
        "Saco de lixo (100L)",
        "Papel higiênico",
        "Lenço de papel",
        "Papel toalha",
        "Shampoo",
        "Condicionador",
        "Sabonete",
        "Sabonete líquido",
        "Creme dental",
        "Fio dental",
        "Escova de dente",
        "Desodorante",
        "Absorvente",
        "Aparelho de barbear",
        "Creme de barbear",
        "Protetor solar",
        "Álcool 70%",
        "Álcool em gel",
        "Cotonete",
    ],
}


class ItensPadraoService:
    @staticmethod
    def popular_se_novo(cur, usuario_id):
        total = ProdutoRepository.count_by_usuario(cur, usuario_id)
        if total > 0:
            return

        itens = [
            (nome, setor)
            for setor, nomes in ITENS_PADRAO.items()
            for nome in nomes
        ]
        ProdutoRepository.bulk_insert_defaults(cur, usuario_id, itens)
